### ISSUE TITLE
Can't record video

### ISSUE THREAD

**Issue by skwzrd** [ispysoftware/iSpy#170]
I get the following error when I try recording anything with the latest version of ispy from https://www.ispyconnect.com/download.aspx on Windows 11.

```
9:56:11 PM | StartSaving: webcam:
-- | --
9:56:11 PM | Open Codec: Open Codec: Writer: Open Codec:Generic error in an external library
9:56:11 PM | Error: Open Codec: Open Codec: Writer: Open Codec:Generic error in an external library
9:56:11 PM | Open Codec: at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
9:56:11 PM | Error: Open Codec: at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
9:56:11 PM | Writer: Open Codec:Generic error in an external library
9:56:11 PM | Can't open h264_nvenc for AV_CODEC_ID_H264
9:56:11 PM | Error: Can't open h264_nvenc for AV_CODEC_ID_H264
9:56:11 PM | Open Codec: Open Codec: Writer: Open Codec:Unknown error occurred
9:56:11 PM | Error: Open Codec: Open Codec: Writer: Open Codec:Unknown error occurred
9:56:11 PM | Open Codec: at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
9:56:11 PM | Error: Open Codec: at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
9:56:11 PM | Writer: Open Codec:Unknown error occurred
9:56:11 PM | Can't open h264_amf for AV_CODEC_ID_H264
9:56:11 PM | Error: Can't open h264_amf for AV_CODEC_ID_H264
9:56:11 PM | Using CPU encoder
9:56:11 PM | Writer: AVIO_OPEN2:Invalid argument
9:56:11 PM | Error: Writer: AVIO_OPEN2:Invalid argument
9:56:11 PM | at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.Open(String filename, Int32 width, Int32 height, AVCodecID videoCodec, Int32 framerate, AVCodecID audioCodec, Int32 crf) at CoreLogic.Objects.Helpers.FrameBufferController.OpenRecording(String videopath, Int32 width, Int32 height, AVCodecID ac, String tags, EventHandler openedCallback, EventHandler closedCallback, EventHandler updateCallback)
9:56:11 PM | Error: at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.Open(String filename, Int32 width, Int32 height, AVCodecID videoCodec, Int32 framerate, AVCodecID audioCodec, Int32 crf) at CoreLogic.Objects.Helpers.FrameBufferController.OpenRecording(String videopath, Int32 width, Int32 height, AVCodecID ac, String tags, EventHandler openedCallback, EventHandler closedCallback, EventHandler updateCallback)
9:56:11 PM | Writer: AVIO_OPEN2:Invalid argument
```

**Comment by ispysoftware** [comment]
hello i'm guessing it can't get permission to write to the location - check the storage locations and make sure it has write access

**Comment by Isawi** [comment]
back version ffmpeg.autogen to 4.2.2.1
