### ISSUE TITLE
Crash - System.NullReferenceException

### ISSUE THREAD

**Issue by j0rn32** [ispysoftware/iSpy#185]
Version: Agent v3.8.9.0
Docker version 20.10.5+dfsg1, build 55c4c88
Linux server1 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

This happens almost daily.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Pixiv.Rtc.AdaptedVideoTrackSource.OnDestruction(IntPtr context)
   at Pixiv.Webrtc.Interop.MediaSourceInterface.Release(IntPtr ptr)
   at Pixiv.Rtc.AdaptedVideoTrackSource.FreePtr()
   at Pixiv.Rtc.DisposablePtr.Finalize()

**Comment by ispysoftware** [comment]
hmm not sure - haven't seen that error before but i'll add some null checks to it - let me know if it persists after the update

**Comment by gcadoret** [comment]
Hello, 
I'm facing the same error. I'm just installing ipsy with docker  (following this tutorial https://mariushosting.com/how-to-install-ispy-on-your-synology-nas/ )

**Comment by ispysoftware** [comment]
what web browser are you using to access it?

**Comment by gcadoret** [comment]
lastest version of Chrome. but I ve unsuccessfully try with edge and Firefox, same error
Thanks
