### ISSUE TITLE
Why Agent DVR says my local ip not private?

### ISSUE THREAD

**Issue by gwjwin** [ispysoftware/iSpy#237]
I'm using Agent DVR v4.2.8.0 on a clean Windows 2008R2 virtual machine (IP:192.167.0.150). This machine has a local lan access but no internet. I extract the Agent_Windows64.zip file without using install.exe. 

Now I can run agent.exe but cannot visit 8090 webpage on other machine. agent shows "Remote access blocked (192.167.0.x), bala bala...." on the webpage , I cannot even visit the webpage on the machine Agent DVR is running using 192.167.0.150:8090, I can only visit the webpage using 127.0.0.1:8090.

Here is the log. Can someone help me understand what the "not private" means, and how agent thinks the connection is not private.

Thanks.

```
Starting...
Detected: Windows64
Using default media location
VLC not in registry, checking default folder location..
Error: VLC version unsupported. Please ensure v3.0.0 (64 bit) or later is instal
led
Registering search path
Libraries Path: C:\Agent_DVR_428\dlls\x64
Initializing
Agent (v4.2.8.0)
Log start
Using WorkStation GC
Init FFmpeg
ffmpeg path: C:\Agent_DVR_428\dlls\x64
Initializing devices
cuda
dxva2
d3d11va
Not linux, Skipping TURN server
Preloading Images
MQTT not configured or enabled
Loaded 0 cameras and 0 mics from C:\Agent_DVR_428\Media\XML\objects.xml
Using default port (8090)
Local Server running on port 8090
Access locally at http://192.167.0.150:8090
Error: IP Lookup: IP Lookup: A socket operation was attempted to an unreachable
network 10.0.2.4:65530
Running at http://localhost:8090
Accepting http connections at http://*:8090/
Error: IP Lookup:    at System.Net.Sockets.Socket.Connect(IPAddress[] addresses,
 Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at CoreLogic.Statics.get_AddressListIPv4()
A socket operation was attempted to an unreachable network 10.0.2.4:65530
IP addresses:
192.167.0.150
found 192.167.0.4
found 192.167.0.15
found 192.167.0.10
found 192.167.0.30
found 192.167.0.40
found 192.167.0.42
found 192.167.0.11
found 192.167.0.41
found 192.167.0.45
found 192.167.0.43
found 192.167.0.16
found 192.167.0.44
found 192.167.0.62
found 192.167.0.60
found 192.167.0.64
found 192.167.0.63
found 192.167.0.70
found 192.167.0.61
found 192.167.0.150
found 192.167.0.151
found 192.167.0.241
found 192.167.0.242
found 192.167.0.240
found 192.167.0.245
found 192.167.0.46
found 192.167.0.247
ZeroConf: ZeroConf Service Started
Not private: 192.167.0.247
Not private: 192.167.0.150
```

**Comment by cleitonmacedosp** [comment]
Does this system work only with private IP? Can't access via VPS with public IP?

**Comment by ispysoftware** [comment]
no not without a business license or a subscription

**Comment by cleitonmacedosp** [comment]
how much is the commercial license?Enviado do meu iPhoneEm 11 de mai. de 2023, à(s) 19:45, sean tearney ***@***.***> escreveu:﻿
no not without a business license or a subscription
