### ISSUE TITLE
Plugins issue on Linux / Docker

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#238]
I have these errors when I try plugins... can you help me figure out what's missing?

<html>
<body>

07:43:43 | Resolved Assembly: /agent/Plugins/Listen/Microsoft.ML.OnnxRuntime.dll
-- | --
07:43:43 | Exception has been thrown by the target of an invocation.
07:43:43 | Error: Exception has been thrown by the target of an invocation.
07:43:43 | at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean ) at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) at System.RuntimeType.CreateInstanceImpl(BindingFlags , Binder , Object[] , CultureInfo ) at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase) at CoreLogic.Utilities.PluginHelper.CheckPlugin(FileInfo dll, List`1& pc)
07:43:43 | Error: at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean ) at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) at System.RuntimeType.CreateInstanceImpl(BindingFlags , Binder , Object[] , CultureInfo ) at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase) at CoreLogic.Utilities.PluginHelper.CheckPlugin(FileInfo dll, List`1& pc)
07:43:43 | Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6'. The system cannot find the file specified.
07:43:43 | Error: Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6'. The system cannot find the file specified.
07:43:43 | at Plugins.Main..ctor() at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
07:43:43 | Error: at Plugins.Main..ctor() at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
07:43:43 | Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6, processorArchitecture=MSIL'. The system cannot find the file specified.
07:43:43 | Error: Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6, processorArchitecture=MSIL'. The system cannot find the file specified.
07:43:43 | at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack , ObjectHandleOnStack , StackCrawlMarkHandle , Boolean , ObjectHandleOnStack , ObjectHandleOnStack ) at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , RuntimeAssembly , StackCrawlMark& , Boolean , AssemblyLoadContext ) at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , StackCrawlMark& , AssemblyLoadContext ) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at CoreLogic.Utilities.PluginHelper.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args) at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler , RuntimeAssembly , String ) at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly , String )
07:43:43 | Error: at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack , ObjectHandleOnStack , StackCrawlMarkHandle , Boolean , ObjectHandleOnStack , ObjectHandleOnStack ) at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , RuntimeAssembly , StackCrawlMark& , Boolean , AssemblyLoadContext ) at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , StackCrawlMark& , AssemblyLoadContext ) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at CoreLogic.Utilities.PluginHelper.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args) at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler , RuntimeAssembly , String ) at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly , String )
07:43:43 | Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6, processorArchitecture=MSIL'. The system cannot find the file specified.

</body>
</html>

**Comment by ispysoftware** [comment]
hmm i haven't had much luck getting listen to work on linux either - looks like you're supposed to download the onnx runtime v1.12.1 from 

https://github.com/microsoft/onnxruntime/releases

"unzip the file and manually copy the files to /usr or /usr/local, either works. Then run ldconfig . in the lib directory which contains libonnxruntime.so."

it's not working here on my pi though - maybe you'll have more luck?
