### ISSUE TITLE
OPEN_INPUT:Invalid data found when processing input

### ISSUE THREAD

**Issue by Fitap** [ispysoftware/iSpy#242]
Hi, 

can't get working IMOU CUE 2 camera and this is my output from logs.html

Anyone could tell me what wrongs?

Thank you.

=====================================================================================================
18:14:33	Starting...
18:14:33	Detected: Linux64
18:14:33	Using default media location
18:14:33	Copying /agent/Content/Masks/demo_mask.png
18:14:33	Copying /agent/Content/sounds/police.wav
18:14:33	Copying /agent/Content/sounds/alsation_bark.wav
18:14:33	Copying /agent/Content/sounds/doorbell.wav
18:14:33	Copying /agent/Content/sounds/alarm.wav
18:14:33	Copying /agent/Content/sounds/airhorn.wav
18:14:33	Copying /agent/Content/sounds/alsationxsiberian_bark.wav
18:14:33	Copying /agent/Content/sounds/cairnterrierbark.wav
18:14:33	Copying /agent/Content/sounds/rottweiler_bark.wav
18:14:33	Copying /agent/Content/sounds/pop.wav
18:14:33	Copying /agent/Content/sounds/wiggle.wav
18:14:33	Copying /agent/Content/sounds/spanielgrowlbark.wav
18:14:35	Creating temp path for opencv in /tmp/
18:14:35	Get com port list
18:14:35	Agent (v4.4.1.0)
18:14:35	Log start
18:14:39	Using WorkStation GC
18:14:39	Init FFmpeg
18:14:39	Looking for ffmpeg in ffmpeg-v5/workspace/lib
18:14:39	Not in there..
18:14:39	Looking for ffmpeg in /usr/local/lib
18:14:39	Not in there..
18:14:39	Looking for ffmpeg in /usr/lib/x86_64-linux-gnu
18:14:39	Found ffmpeg in /usr/lib/x86_64-linux-gnu
18:14:39	ffmpeg path: /usr/lib/x86_64-linux-gnu
18:14:39	Initializing devices
18:14:39	vdpau
18:14:39	cuda
18:14:39	vaapi
18:14:39	qsv
18:14:39	drm
18:14:39	opencl
18:14:39	vulkan
18:14:39	Found 0 devices
18:14:39	call arecord -l
18:14:39	Preloading Images
18:14:39	Turn Server accepting connections at 172.17.0.2:3478 using range 50000-50010)
18:14:39	MQTT not configured or enabled
18:14:40	Loaded 1 cameras and 0 mics from /agent/Media/XML/objects.xml
18:14:40	Using default port (8090)
18:14:40	Local Server running on port 8090
18:14:40	Access locally at http://172.17.0.2:8090
18:14:40	IP addresses:
18:14:40	172.17.0.2
18:14:40	Accepting http connections at http://*:8090/
18:14:40	found 172.17.0.2
18:14:40	found 172.17.0.1
18:14:40	Running at http://localhost:8090
18:14:40	ZeroConf: ZeroConf Service Started
18:14:44	Using comms server https://rtcfunc.azurewebsites.net
18:14:48	Connecting service (https://rtcfunc.azurewebsites.net)
18:14:51	rtc:added servers
18:14:51	rtc:onsuccessanswer
18:14:51	ICE state: Checking
18:14:51	ICE state: Connected
18:14:51	rtc:ondatachannelstatechange (serverdata: Open)
18:14:51	rtc: opened serverdata
18:14:51	rtc:ondatachannelstatechange (talk: Open)
18:14:51	rtc: opened talk
18:14:52	Connected to SignalR. Waiting for hello...
18:14:53	SignalR: Services Connected
18:14:53	Welcome: Fitap
18:14:53	Connected - access this server remotely via https://www.ispyconnect.com/
18:15:48	Discovery (GetServices): ONVIF v1.0
18:15:48	Discovery: Using Media Version 1
18:15:48	Discovery: Media available at http://192.168.0.31/onvif/media_service
18:15:48	Discovery: PTZ available at http://192.168.0.31/onvif/ptz_service
18:15:48	Discovery: Events available at http://192.168.0.31/onvif/event_service
18:16:02	Enable: Camera 1: Enabled
18:16:02	Discovery (GetServices): Camera 1: ONVIF v1.0
18:16:02	Discovery: Camera 1: Using Media Version 1
18:16:02	Discovery: Camera 1: Media available at http://192.168.0.31/onvif/media_service
18:16:02	Discovery: Camera 1: PTZ available at http://192.168.0.31/onvif/ptz_service
18:16:02	Discovery: Camera 1: Events available at http://192.168.0.31/onvif/event_service
18:16:04	ONVIF Presets: Camera 1: Presets not supported
18:16:04	Error: ONVIF Presets: Camera 1: Presets not supported
18:16:04	open (live): Camera 1: Trying UDP
18:16:04	Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:04	Error: Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:04	Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:04	Error: Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:04	Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:04	SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:04	Error: SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:04	SourcePlayingFinished: Camera 1: Playing finished (SourceError)
18:16:04	Reconnect: Camera 1: Reconnecting in 2s
18:16:06	intervals: Camera 1: Reconnecting
18:16:06	intervals: Camera 1: Reconnect Exit
18:16:07	Discovery (GetServices): Camera 1: ONVIF v1.0
18:16:07	Discovery: Camera 1: Using Media Version 1
18:16:07	Discovery: Camera 1: Media available at http://192.168.0.31/onvif/media_service
18:16:07	Discovery: Camera 1: PTZ available at http://192.168.0.31/onvif/ptz_service
18:16:07	Discovery: Camera 1: Events available at http://192.168.0.31/onvif/event_service
18:16:09	ONVIF Presets: Camera 1: Presets not supported
18:16:09	Error: ONVIF Presets: Camera 1: Presets not supported
18:16:09	open (live): Camera 1: Trying TCP
18:16:09	Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:09	Error: Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:09	Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:09	Error: Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:09	Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:09	SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:09	Error: SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:09	SourcePlayingFinished: Camera 1: Playing finished (SourceError)
18:16:09	Reconnect: Camera 1: Reconnecting in 5s
18:16:15	intervals: Camera 1: Reconnecting
18:16:15	intervals: Camera 1: Reconnect Exit
18:16:15	Discovery (GetServices): Camera 1: ONVIF v1.0
18:16:15	Discovery: Camera 1: Using Media Version 1
18:16:15	Discovery: Camera 1: Media available at http://192.168.0.31/onvif/media_service
18:16:15	Discovery: Camera 1: PTZ available at http://192.168.0.31/onvif/ptz_service
18:16:15	Discovery: Camera 1: Events available at http://192.168.0.31/onvif/event_service
18:16:17	ONVIF Presets: Camera 1: Presets not supported
18:16:17	Error: ONVIF Presets: Camera 1: Presets not supported
18:16:17	open (live): Camera 1: Trying UDP
18:16:17	Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:17	Error: Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:17	Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:17	Error: Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:17	Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:17	SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:17	Error: SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:17	SourcePlayingFinished: Camera 1: Playing finished (SourceError)
18:16:17	Reconnect: Camera 1: Reconnecting in 10s
18:16:27	intervals: Camera 1: Reconnecting
18:16:27	intervals: Camera 1: Reconnect Exit
18:16:28	Discovery (GetServices): Camera 1: ONVIF v1.0
18:16:28	Discovery: Camera 1: Using Media Version 1
18:16:28	Discovery: Camera 1: Media available at http://192.168.0.31/onvif/media_service
18:16:28	Discovery: Camera 1: PTZ available at http://192.168.0.31/onvif/ptz_service
18:16:28	Discovery: Camera 1: Events available at http://192.168.0.31/onvif/event_service
18:16:29	ONVIF Presets: Camera 1: Presets not supported
18:16:29	Error: ONVIF Presets: Camera 1: Presets not supported
18:16:29	open (live): Camera 1: Trying TCP
18:16:29	Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:29	Error: Camera 1: DoStart: Camera 1: DoStart: Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:29	Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:29	Error: Camera 1: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
18:16:29	Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:29	SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:29	Error: SourceError: Camera 1: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 1: OPEN_INPUT:Invalid data found when processing input
18:16:29	SourcePlayingFinished: Camera 1: Playing finished (SourceError)
18:16:29	Reconnect: Camera 1: Reconnecting in 30s

=====================================================================================================

**Comment by Fitap** [comment]
I perform factory reset to the device and now looks like works fine.
