### ISSUE TITLE
FaceRecognizer Exception

### ISSUE THREAD

**Issue by gazibastug** [ispysoftware/iSpy#267]
AgentDVR -> OS: Windows 
I wanted to add a picture for face recognition.

LoadJson: A task was canceled.    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CoreLogic.AI.FaceRecognizer.<ListFaces>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CoreLogic.Server.JsonProcessor.<LoadJson>d__11.MoveNext()

**Comment by ispysoftware** [comment]
Usually means FaceRecognition isn't running on CodeProject AI - check the AI server logs

**Comment by gazibastug** [comment]
Thanks for your help.

Yes, the error came from there. :)
